version: 2

builds:
  - binary: statusline
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
      - mips
      - mipsle
      - ppc64le
      - s390x
      - riscv64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: riscv64
      - goos: freebsd
        goarch: mips
      - goos: freebsd
        goarch: mipsle
      - goos: freebsd
        goarch: ppc64le
      - goos: freebsd
        goarch: s390x
      - goos: freebsd
        goarch: riscv64
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: mips
      - goos: openbsd
        goarch: mipsle
      - goos: openbsd
        goarch: ppc64le
      - goos: openbsd
        goarch: s390x
      - goos: openbsd
        goarch: riscv64
      - goos: netbsd
        goarch: arm
      - goos: netbsd
        goarch: mips
      - goos: netbsd
        goarch: mipsle
      - goos: netbsd
        goarch: ppc64le
      - goos: netbsd
        goarch: s390x
      - goos: netbsd
        goarch: riscv64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
